services:
  nginx:
    build: requirements/nginx/.
    restart: always
    image: nginx
    container_name: nginx
    env_file:
      - /home/vejurick/Desktop/.env
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/vejurick/data/web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    env_file:
      - /home/vejurick/Desktop/.env
    restart: always
    container_name: wp-php
    secrets:
      - db_user_password
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_password
    depends_on:
      - mariadb
    volumes:
      - /home/vejurick/data/web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    restart: always
    image: mariadb
    env_file:
      - /home/vejurick/Desktop/.env
    container_name: mariadb
    secrets:
      - db_root_password
      - db_user_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - /home/vejurick/data/database:/var/lib/mysql
    networks:
      inception:
networks:
  inception:
    name: inception
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
